/**
 * ai-monitoring.interfaces.ts
 *
 * Extension-point interfaces for AI system observability in MyOrtho.tech.
 * These are ARCHITECTURE definitions — no runtime implementations exist here.
 *
 * Concrete implementations (e.g. a Prometheus exporter, a TimescaleDB writer,
 * or a DataDog reporter) must satisfy the IAIMonitoringService contract and
 * the storage/aggregation contracts implied by these data types.
 *
 * Design intent:
 *   - Inference metrics are written at per-call granularity and later
 *     aggregated into ModelPerformanceReports over configurable windows.
 *   - GPU metrics are sampled on an interval (reportingIntervalMs) and stored
 *     independently from inference metrics.
 *   - All timestamps are ISO-8601 strings to avoid timezone ambiguity in
 *     multi-region deployments.
 */

// ---------------------------------------------------------------------------
// Per-inference metrics
// ---------------------------------------------------------------------------

/**
 * Single inference telemetry record.
 * Produced by the inference adapter immediately after each model call
 * and forwarded to IAIMonitoringService.recordInference.
 */
export interface InferenceMetric {
  /** Registry ID of the model that was invoked. */
  modelId: string;

  /** End-to-end wall-clock inference latency in milliseconds. */
  latencyMs: number;

  /** Byte size of the serialised input payload sent to the model. */
  inputSizeBytes: number;

  /** Byte size of the serialised output payload returned by the model. */
  outputSizeBytes: number;

  /** Whether the inference call completed without error. */
  success: boolean;

  /**
   * Human-readable error description when success === false.
   * null on successful calls.
   */
  errorMessage: string | null;

  /**
   * Compute device that executed the inference.
   * Examples: 'cpu', 'cuda:0', 'cuda:1'
   */
  deviceType: string;

  /** ISO-8601 timestamp of the inference call. */
  timestamp: string;
}

// ---------------------------------------------------------------------------
// GPU telemetry
// ---------------------------------------------------------------------------

/**
 * Point-in-time GPU utilisation snapshot for a single physical device.
 * Sampled by the monitoring service at the configured reportingIntervalMs.
 *
 * Values sourced from NVIDIA Management Library (NVML) via nvidia-smi or
 * equivalent GPU monitoring API.
 */
export interface GPUMetrics {
  /**
   * Platform-specific device identifier.
   * Convention: 'cuda:<index>' (e.g. 'cuda:0') for NVIDIA GPUs.
   */
  deviceId: string;

  /**
   * GPU compute core utilisation as a percentage.
   * Range: [0, 100]
   */
  utilizationPct: number;

  /**
   * GPU VRAM currently consumed in megabytes.
   * Must be ≤ memoryTotalMb.
   */
  memoryUsedMb: number;

  /**
   * Total installed GPU VRAM in megabytes (fixed hardware spec).
   * e.g. 24576 for an RTX 3090 (24 GB).
   */
  memoryTotalMb: number;

  /**
   * GPU junction temperature in degrees Celsius.
   * Values consistently above ~83 °C (NVIDIA throttle threshold) should
   * trigger a cooling alert.
   */
  temperatureC: number;

  /** ISO-8601 timestamp when this sample was captured. */
  timestamp: string;
}

// ---------------------------------------------------------------------------
// Aggregated performance report
// ---------------------------------------------------------------------------

/**
 * Aggregated performance summary for a single model over a time window.
 * Generated by the monitoring service and used for dashboards, SLA
 * reporting, and drift-detection pipelines.
 *
 * Latency percentiles follow the convention of excluding outliers that
 * represent infra issues (e.g. pod evictions) rather than model behaviour.
 */
export interface ModelPerformanceReport {
  /** Registry ID of the model this report covers. */
  modelId: string;

  /** ISO-8601 start of the aggregation window. */
  windowStartAt: string;

  /** ISO-8601 end of the aggregation window. */
  windowEndAt: string;

  /** Total number of inference calls made in the window. */
  totalInferences: number;

  /**
   * Fraction of calls that completed without error.
   * Range: [0.0, 1.0]
   * Example: 0.997 = 99.7% success rate.
   */
  successRate: number;

  /**
   * Arithmetic mean latency across all successful calls in milliseconds.
   * Computed only over successful inferences (errorMessage === null).
   */
  avgLatencyMs: number;

  /**
   * 95th-percentile latency in milliseconds.
   * Key SLA metric — monitor this rather than avgLatencyMs alone.
   */
  p95LatencyMs: number;

  /**
   * Mean model-reported confidence score across successful inferences.
   * Range: [0.0, 1.0]; null when the model does not emit confidence.
   */
  avgConfidence: number | null;

  /**
   * Mean segmentation accuracy (Dice coefficient) when ground-truth
   * labels are available from the clinician feedback loop.
   * Range: [0.0, 1.0]; null when no labelled production samples exist
   * for this window.
   *
   * Reference: Dice (1945) — "Measures of the Amount of Ecologic
   * Association Between Species", Ecology 26(3).
   */
  avgSegmentationAccuracy: number | null;
}

// ---------------------------------------------------------------------------
// Monitoring configuration
// ---------------------------------------------------------------------------

/**
 * Runtime configuration for the AI monitoring subsystem.
 * Loaded from environment variables or a config service at startup.
 */
export interface AIMonitoringConfig {
  /**
   * Number of days to retain raw InferenceMetric records before archival
   * or deletion. Aggregated reports may be kept longer.
   */
  metricsRetentionDays: number;

  /**
   * Model drift score threshold above which an alert is raised.
   * Maps to ModelDriftMetrics.alertThreshold.
   * Recommended starting value: 0.2 (PSI interpretation convention).
   */
  alertOnDriftThreshold: number;

  /**
   * Inference error-rate threshold above which an alert is raised.
   * Expressed as a fraction [0.0, 1.0].
   * Example: 0.05 triggers an alert when more than 5% of calls fail.
   */
  alertOnErrorRateThreshold: number;

  /**
   * Whether GPU metrics sampling is active.
   * Set to false in CPU-only or development environments.
   */
  gpuMonitoringEnabled: boolean;

  /**
   * Interval in milliseconds between GPU metric samples and
   * performance-report aggregation cycles.
   * Minimum recommended: 10_000 ms (10 s).
   */
  reportingIntervalMs: number;
}

// ---------------------------------------------------------------------------
// Monitoring service interface
// ---------------------------------------------------------------------------

/**
 * Service contract for the AI observability subsystem.
 *
 * ARCHITECTURE EXTENSION POINT: no concrete implementation exists in the
 * current codebase. Implementations may write to PostgreSQL/TimescaleDB,
 * Prometheus push-gateway, DataDog, etc.
 *
 * All methods are async to allow non-blocking fire-and-forget recording
 * from the hot inference path.
 */
export interface IAIMonitoringService {
  /**
   * Records a single inference telemetry event.
   * Must not throw — inference callers should not fail due to monitoring errors.
   * Implementations should swallow and log any internal storage errors.
   *
   * @param metric - Telemetry for one inference call.
   */
  recordInference(metric: InferenceMetric): Promise<void>;

  /**
   * Records a point-in-time GPU utilisation snapshot.
   * Called by the GPU polling loop at the configured interval.
   *
   * @param metrics - Snapshot from a single GPU device.
   */
  recordGPUMetrics(metrics: GPUMetrics): Promise<void>;

  /**
   * Returns an aggregated performance report for a model over a time range.
   *
   * @param modelId - Registry ID of the model.
   * @param windowStartAt - ISO-8601 start of the aggregation window.
   * @param windowEndAt - ISO-8601 end of the aggregation window.
   * @returns Aggregated report or null if no data exists for the window.
   */
  getPerformanceReport(
    modelId: string,
    windowStartAt: string,
    windowEndAt: string,
  ): Promise<ModelPerformanceReport | null>;

  /**
   * Returns the most recent raw InferenceMetric records for a model,
   * newest-first, limited to the requested count.
   *
   * @param modelId - Registry ID of the model.
   * @param limit - Maximum number of records to return (default: 100).
   */
  getRecentMetrics(modelId: string, limit?: number): Promise<InferenceMetric[]>;
}
