import {
  Injectable,
  Inject,
  BadRequestException,
  NotFoundException,
  ForbiddenException,
  ServiceUnavailableException,
  Logger,
} from '@nestjs/common';
import type { Pool } from 'pg';
import { PG_POOL } from '../database/database.module';
import { WorkflowService } from '../workflow/workflow.service';

const AI_DISCLAIMER =
  'AI treatment planning recommendations are research-stage only. ' +
  'Not clinically validated. All plans require clinical review and doctor approval.';

export interface CreatePlanDto {
  estimatedStages?: number;
  aiRecommendationNotes?: string;
  iprDetails?: Record<string, unknown>;
}

export interface CreateStageDto {
  stageNumber: number;
  maxillaryMeshPath?: string;
  mandibularMeshPath?: string;
  movements?: Record<string, unknown>;
}

@Injectable()
export class TreatmentPlansService {
  private readonly logger = new Logger(TreatmentPlansService.name);

  constructor(
    @Inject(PG_POOL) private readonly pool: Pool,
    private readonly workflowService: WorkflowService,
  ) {}

  async listPlans(caseId: string, orgId: string) {
    await this.verifyCaseOwnership(caseId, orgId);
    const { rows } = await this.pool.query(
      `SELECT id, case_id, doctor_approval, approved_at, estimated_stages,
              ai_recommendation_notes, ipr_details, created_at, updated_at
       FROM treatment_plans WHERE case_id = $1 ORDER BY created_at DESC`,
      [caseId],
    );
    return rows.map((r) => ({ ...this.formatPlan(r), disclaimer: AI_DISCLAIMER }));
  }

  async createPlan(caseId: string, orgId: string, createdBy: string, dto: CreatePlanDto) {
    await this.verifyCaseOwnership(caseId, orgId);
    const { rows } = await this.pool.query(
      `INSERT INTO treatment_plans
         (case_id, created_by, estimated_stages, ai_recommendation_notes, ipr_details)
       VALUES ($1, $2, $3, $4, $5)
       RETURNING id, created_at`,
      [
        caseId,
        createdBy,
        dto.estimatedStages ?? 0,
        dto.aiRecommendationNotes ?? null,
        JSON.stringify(dto.iprDetails ?? {}),
      ],
    );
    this.logger.log(`Treatment plan ${rows[0].id as string} created for case ${caseId}`);
    return { id: rows[0].id as string, caseId, createdAt: rows[0].created_at as Date, disclaimer: AI_DISCLAIMER };
  }

  async getPlan(planId: string, caseId: string, orgId: string) {
    await this.verifyCaseOwnership(caseId, orgId);
    const { rows } = await this.pool.query(
      `SELECT id, case_id, doctor_approval, doctor_signature, approved_at,
              estimated_stages, ai_recommendation_notes, ipr_details, created_at, updated_at
       FROM treatment_plans WHERE id = $1 AND case_id = $2`,
      [planId, caseId],
    );
    if (!rows[0]) throw new NotFoundException('Treatment plan not found');
    return { ...this.formatPlan(rows[0]), disclaimer: AI_DISCLAIMER };
  }

  async approvePlan(
    planId: string,
    caseId: string,
    orgId: string,
    doctorId: string,
    actorRole: string,
    actorEmail: string,
    signature: string,
  ) {
    await this.verifyCaseOwnership(caseId, orgId);

    // Block approval if any stage was generated by the rule-based scaffold.
    // _is_simulated=true is embedded in movement_data JSON — check with Postgres jsonb cast.
    const { rows: simRows } = await this.pool.query(
      `SELECT id FROM aligner_stages
       WHERE treatment_plan_id = $1
         AND (movement_data::jsonb ->> '_is_simulated')::boolean = true
       LIMIT 1`,
      [planId],
    );
    if (simRows.length > 0) {
      throw new BadRequestException(
        'This treatment plan contains simulated scaffold stages and cannot be approved. ' +
        'Replace stages with AI-computed data before submission for approval.',
      );
    }

    // Approve the treatment plan in its own transaction.
    const client = await this.pool.connect();
    let approvedRow: Record<string, unknown>;
    try {
      await client.query('BEGIN');
      const { rows } = await client.query(
        `UPDATE treatment_plans
         SET doctor_approval = true, doctor_signature = $1, approved_at = now(), updated_at = now()
         WHERE id = $2 AND case_id = $3 AND doctor_approval = false
         RETURNING id, doctor_approval, approved_at`,
        [signature, planId, caseId],
      );
      if (!rows[0]) {
        await client.query('ROLLBACK');
        throw new NotFoundException('Treatment plan not found or already approved');
      }
      approvedRow = rows[0];
      await client.query('COMMIT');
    } catch (err) {
      await client.query('ROLLBACK');
      throw err;
    } finally {
      client.release();
    }

    this.logger.log(`Plan ${planId} approved by ${doctorId} for case ${caseId}`);

    // Advance case status through WorkflowService so the transition is audited
    // and recorded in workflow_events. The case may already be past 'planning'
    // (e.g. if approved twice) — catch and log rather than surfacing to the caller.
    try {
      await this.workflowService.transition({
        caseId,
        toStatus: 'clinical_review',
        actorId: doctorId,
        actorRole,
        orgId,
        actorEmail,
        notes: `Treatment plan ${planId} approved`,
      });
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : String(err);
      this.logger.warn(`Case ${caseId} status not advanced to clinical_review: ${msg}`);
    }

    return {
      id: approvedRow['id'] as string,
      doctorApproval: approvedRow['doctor_approval'] as boolean,
      approvedAt: approvedRow['approved_at'] as Date,
    };
  }

  // ── Aligner Stages ───────────────────────────────────────────────────────────

  async listStages(planId: string, caseId: string, orgId: string) {
    await this.verifyCaseOwnership(caseId, orgId);
    const { rows } = await this.pool.query(
      `SELECT s.id, s.treatment_plan_id, s.stage_number, s.movement_data, s.created_at
       FROM aligner_stages s
       JOIN treatment_plans tp ON tp.id = s.treatment_plan_id
       WHERE s.treatment_plan_id = $1 AND tp.case_id = $2
       ORDER BY s.stage_number`,
      [planId, caseId],
    );
    return rows.map((r) => ({
      id: r['id'] as string,
      planId: r['treatment_plan_id'] as string,
      stageNumber: r['stage_number'] as number,
      movements: r['movement_data'] as Record<string, unknown>,
      createdAt: r['created_at'] as Date,
    }));
  }

  async createStage(planId: string, caseId: string, orgId: string, dto: CreateStageDto) {
    await this.verifyCaseOwnership(caseId, orgId);
    const { rows: planRows } = await this.pool.query(
      `SELECT id FROM treatment_plans WHERE id = $1 AND case_id = $2`,
      [planId, caseId],
    );
    if (!planRows[0]) throw new ForbiddenException('Plan not found in this case');

    const { rows } = await this.pool.query(
      `INSERT INTO aligner_stages
         (treatment_plan_id, case_id, stage_number, movement_data)
       VALUES ($1, $2, $3, $4)
       ON CONFLICT (treatment_plan_id, stage_number) DO UPDATE
         SET movement_data = EXCLUDED.movement_data
       RETURNING id, stage_number, created_at`,
      [
        planId,
        caseId,
        dto.stageNumber,
        JSON.stringify(dto.movements ?? {}),
      ],
    );
    return {
      id: rows[0].id as string,
      planId,
      stageNumber: rows[0].stage_number as number,
      createdAt: rows[0].created_at as Date,
    };
  }

  async updatePlan(planId: string, caseId: string, orgId: string, dto: { estimatedStages?: number; aiRecommendationNotes?: string }) {
    await this.verifyCaseOwnership(caseId, orgId);
    const sets: string[] = [];
    const vals: unknown[] = [];
    if (dto.estimatedStages !== undefined) { sets.push(`estimated_stages = $${sets.length + 1}`); vals.push(dto.estimatedStages); }
    if (dto.aiRecommendationNotes !== undefined) { sets.push(`ai_recommendation_notes = $${sets.length + 1}`); vals.push(dto.aiRecommendationNotes); }
    if (sets.length === 0) throw new Error('Nothing to update');
    sets.push(`updated_at = now()`);
    vals.push(planId, caseId);
    const { rows } = await this.pool.query(
      `UPDATE treatment_plans SET ${sets.join(', ')} WHERE id = $${vals.length - 1} AND case_id = $${vals.length} AND doctor_approval = false RETURNING id`,
      vals,
    );
    if (!rows[0]) throw new NotFoundException('Treatment plan not found');
    return { id: rows[0].id as string, updated: true };
  }

  async bulkUpsertStages(planId: string, caseId: string, orgId: string, stages: CreateStageDto[]) {
    await this.verifyCaseOwnership(caseId, orgId);
    const { rows: planRows } = await this.pool.query(
      `SELECT id FROM treatment_plans WHERE id = $1 AND case_id = $2`,
      [planId, caseId],
    );
    if (!planRows[0]) throw new NotFoundException('Plan not found in this case');
    const results = await Promise.all(stages.map((s) => this.createStage(planId, caseId, orgId, s)));
    return { upserted: results.length, stages: results };
  }

  async generateStages(planId: string, caseId: string, orgId: string, stageCount?: number) {
    await this.verifyCaseOwnership(caseId, orgId);

    const aiUrl = process.env['TREATMENT_PLAN_AI_URL'];
    const fallbackEnabled = process.env['TREATMENT_PLAN_STAGE_FALLBACK_ENABLED'] === 'true';

    if (!aiUrl && !fallbackEnabled) {
      throw new ServiceUnavailableException(
        'Automated stage generation requires TREATMENT_PLAN_AI_URL to be configured. ' +
        'Use manual stage entry or set TREATMENT_PLAN_STAGE_FALLBACK_ENABLED=true to enable ' +
        'a rule-based scaffold (stages will be marked simulated and cannot be approved or exported).',
      );
    }

    const { rows: planRows } = await this.pool.query(
      `SELECT id, estimated_stages FROM treatment_plans WHERE id = $1 AND case_id = $2`,
      [planId, caseId],
    );
    if (!planRows[0]) throw new NotFoundException('Treatment plan not found');

    const n = Math.max(1, Math.min(60, stageCount ?? (planRows[0]['estimated_stages'] as number) ?? 20));

    // Pull crowding context from clinical analysis if available
    const { rows: analysisRows } = await this.pool.query(
      `SELECT upper_crowding_mm, lower_crowding_mm FROM case_analyses WHERE case_id = $1 ORDER BY created_at DESC LIMIT 1`,
      [caseId],
    );
    const upperCrowding = (analysisRows[0]?.['upper_crowding_mm'] as number | null) ?? 4;
    const lowerCrowding = (analysisRows[0]?.['lower_crowding_mm'] as number | null) ?? 3;

    // FDI arch teeth (exclude 3rd molars for aligner planning)
    const UPPER = [11,12,13,14,15,16,17,21,22,23,24,25,26,27];
    const LOWER = [31,32,33,34,35,36,37,41,42,43,44,45,46,47];

    this.logger.warn(
      '⚠️  TREATMENT PLAN STAGE FALLBACK ACTIVE: movements generated by deterministic scaffold, ' +
      'NOT real biomechanical computation. Stages are marked is_simulated=true and cannot be ' +
      `approved or exported. Plan ${planId}, case ${caseId}.`,
    );

    // Deterministic per-tooth total movement from plan id + fdi seed
    const det = (s: number) => (((s * 9301 + 49297) % 233280) / 233280);
    const planSeed = planId.split('').reduce((a, c) => a + c.charCodeAt(0), 0);

    const totals: Record<number, { mesialMm: number; distalMm: number; buccalMm: number; lingualMm: number; extrusionMm: number; intrusionMm: number; torqueDeg: number }> = {};
    for (const fdi of [...UPPER, ...LOWER]) {
      const isUpper = fdi < 30;
      const crowding = isUpper ? upperCrowding : lowerCrowding;
      const pos = fdi % 10;
      const isFront = pos <= 3;
      const scale = isFront ? crowding * 0.12 : crowding * 0.04;
      const s = fdi * 1337 + planSeed;
      const sign = (x: number) => det(x) > 0.5 ? 1 : -1;
      totals[fdi] = {
        mesialMm:   parseFloat((det(s) * scale * sign(s + 1)).toFixed(3)),
        distalMm:   parseFloat((det(s + 2) * scale * 0.6 * sign(s + 3)).toFixed(3)),
        buccalMm:   parseFloat((det(s + 4) * scale * 0.35).toFixed(3)),
        lingualMm:  parseFloat((det(s + 5) * scale * 0.25).toFixed(3)),
        extrusionMm: parseFloat((det(s + 6) * 0.4).toFixed(3)),
        intrusionMm: parseFloat((det(s + 7) * 0.3).toFixed(3)),
        torqueDeg:  parseFloat((det(s + 8) * 4 * sign(s + 9)).toFixed(1)),
      };
    }

    // Build all stages in memory then batch-INSERT in a single query
    // is_simulated=true prevents approval and export of scaffold stages
    const stageDtos: Array<{ stageNumber: number; movementData: string }> = [];
    for (let i = 1; i <= n; i++) {
      const f = i / n;
      const movements: Record<string, Record<string, number>> = {};
      for (const fdi of [...UPPER, ...LOWER]) {
        const t = totals[fdi]!;
        movements[String(fdi)] = {
          mesialMm:    parseFloat((t.mesialMm * f).toFixed(3)),
          distalMm:    parseFloat((t.distalMm * f).toFixed(3)),
          buccalMm:    parseFloat((t.buccalMm * f).toFixed(3)),
          lingualMm:   parseFloat((t.lingualMm * f).toFixed(3)),
          extrusionMm: parseFloat((t.extrusionMm * f).toFixed(3)),
          intrusionMm: parseFloat((t.intrusionMm * f).toFixed(3)),
          torqueDeg:   parseFloat((t.torqueDeg * f).toFixed(1)),
        };
      }
      stageDtos.push({ stageNumber: i, movementData: JSON.stringify({ ...movements, _is_simulated: true }) });
    }

    // Single batch INSERT — replaces N individual queries
    const valueParams = stageDtos
      .map((_, idx) => `($1, $2, $${3 + idx * 2}, $${4 + idx * 2})`)
      .join(', ');
    const flatValues: unknown[] = [planId, caseId];
    for (const s of stageDtos) {
      flatValues.push(s.stageNumber, s.movementData);
    }
    await this.pool.query(
      `INSERT INTO aligner_stages (treatment_plan_id, case_id, stage_number, movement_data)
       VALUES ${valueParams}
       ON CONFLICT (treatment_plan_id, stage_number) DO UPDATE
         SET movement_data = EXCLUDED.movement_data`,
      flatValues,
    );

    this.logger.log(`Generated ${n} simulated scaffold stages for plan ${planId} (case ${caseId}) via batch INSERT`);
    return {
      generated: n,
      planId,
      caseId,
      is_simulated: true,
      warning: 'Stages generated by rule-based scaffold. Replace with AI-computed stages before approval.',
    };
  }

  private async verifyCaseOwnership(caseId: string, orgId: string) {
    const { rows } = await this.pool.query(
      `SELECT c.id FROM cases c
       JOIN patients p ON p.id = c.patient_id
       WHERE c.id = $1 AND p.organization_id = $2`,
      [caseId, orgId],
    );
    if (!rows[0]) throw new NotFoundException('Case not found');
  }

  private formatPlan(r: Record<string, unknown>) {
    return {
      id: r['id'] as string,
      caseId: r['case_id'] as string,
      doctorApproval: r['doctor_approval'] as boolean,
      approvedAt: r['approved_at'] as Date | null,
      estimatedStages: r['estimated_stages'] as number,
      aiRecommendationNotes: r['ai_recommendation_notes'] as string | null,
      iprDetails: r['ipr_details'] as Record<string, unknown>,
      createdAt: r['created_at'] as Date,
      updatedAt: r['updated_at'] as Date,
    };
  }
}
